# Generated by Django 5.1.3 on 2024-11-10 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('description', models.TextField(verbose_name='Описание объекта')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (кв.м)')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб.)')),
                ('status', models.CharField(choices=[('available', 'Свободно'), ('rented', 'Сдано')], default='available', max_length=10, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('signed_on', models.DateField(auto_now_add=True, verbose_name='Дата заключения договора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='property_management.propertylisting', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(verbose_name='Дата просмотра')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждаю')], default='pending', max_length=10, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to='property_management.propertylisting', verbose_name='Объект')),
            ],
        ),
    ]
